apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBiding
metadata: 
  name: admin-user 
roleRef:
  apiGroup: rbac.authorization.k8s.io 
  kind: ClusterRole 
  name: cluster-admin
subjects: 
- kind: ServiceAccount 
  name: admin-user 
  namespace: kube-system 
  