apiVersion: batch/v1beta1
kind: CronJob
metadata: 
  name: giropops-cron
spec: 
  schedule: "*/1 * * * *"
  jobTemplate:
    spec: 
      template: 
        spec: 
          containers:
          - name: giropops-cron
            image: busy-box
            args: 
            - /bin/bash
            - -c 
            - date; echo Bem Vindo ao Descomplicando Kubernetes - LinuxTips ;sleep 30
          restartPolicy: Onfailure
          
